BASE: ['']

TOOLBOX_MODE: "train_and_test"

TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 30
  LR: 1e-3
  MODEL_FILE_NAME: UBFC_DeepPhys_Original
  PLOT_LOSSES_AND_LR: True

  DATA:
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: True
    DATA_FORMAT: NDCHW

    DATA_PATH: "/Volumes/Intenso/UBFC-rPPG"
    CACHED_PATH: "./cache/ubfc_baseline"
    FILE_LIST_PATH: "./data/file_lists/ubfc_baseline"

    BEGIN: 0.0
    END: 0.7   # ✅ 70% Train

    PREPROCESS:
      USE_MSR: False
      MSR:
        SCALES: [ 15, 80, 250 ]
        GAIN: 1.0
        OFFSET: 0.0
      DATA_TYPE: ['DiffNormalized','Standardized']
      DATA_AUG: ['None']
      LABEL_TYPE: DiffNormalized

      DO_CHUNK: True
      CHUNK_LENGTH: 300

      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5

        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False

      RESIZE:
        H: 36
        W: 36


VALID:
  DATA:
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: True
    DATA_FORMAT: NDCHW

    DATA_PATH: "/Volumes/Intenso/UBFC-rPPG"
    CACHED_PATH: "./cache/ubfc_baseline"

    FILE_LIST_PATH: "./data/file_lists/ubfc_baseline"

    BEGIN: 0.7
    END: 0.85   # ✅ 15% Validation

    PREPROCESS:
      USE_MSR: False
      MSR:
        SCALES: [ 15, 80, 250 ]
        GAIN: 1.0
        OFFSET: 0.0
      DATA_TYPE: ['DiffNormalized','Standardized']
      DATA_AUG: ['None']
      LABEL_TYPE: DiffNormalized

      DO_CHUNK: True
      CHUNK_LENGTH: 300

      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5

        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False

      RESIZE:
        H: 36
        W: 36


TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA']
  USE_LAST_EPOCH: False

  DATA:
    FS: 30
    DATASET: UBFC-rPPG
    DO_PREPROCESS: True
    DATA_FORMAT: NDCHW

    DATA_PATH: "/Volumes/Intenso/UBFC-rPPG"
    CACHED_PATH: "./cache/ubfc_baseline"

    FILE_LIST_PATH: "./data/file_lists/ubfc_baseline"

    BEGIN: 0.85
    END: 1.0   # ✅ 15% Test (kein Leakage!)

    PREPROCESS:
      USE_MSR: False
      MSR:
        SCALES: [ 15, 80, 250 ]
        GAIN: 1.0
        OFFSET: 0.0
      DATA_TYPE: ['DiffNormalized','Standardized']
      LABEL_TYPE: DiffNormalized

      DO_CHUNK: True
      CHUNK_LENGTH: 300

      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5

        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 30
          USE_MEDIAN_FACE_BOX: False

      RESIZE:
        H: 36
        W: 36


DEVICE: cpu
NUM_OF_GPU_TRAIN: 1

LOG:
  PATH: runs/exp

MODEL:
  DROP_RATE: 0.2
  NAME: DeepPhys
  TDCM:
    ENABLE: False
    CHANNELS: 128
    DROPOUT: 0.1
    KERNEL_SHORT: 3
    KERNEL_MID: 5
    KERNEL_LONG: 7
    DILATION_MID: 2
    DILATION_LONG: 3

INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"

  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False
    WINDOW_SIZE: 30

  MODEL_PATH: ""